stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t booking-app-image:0.7 .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose up -d
