stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV_DOCKER} .env
    - cp ${ENV_TEST} .test.env
  script:
    - docker build -t booking-app-image:0.7 .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose --file docker-compose-ci.yml up -d
    - docker exec nginx-booking nginx -s reload
