stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_DOCKER} .env.docker
    - cp ${ENV_TEST} .test.env
  script:
    - docker build -t booking-app-image:0.7 .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose up -d
