stages:
  - build
#  - lint
#  - format
#  - typecheck
#  - migrate
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV_DOCKER} .env
    - cp ${ENV_TEST} .test.env
  script:
    - docker build -t booking-app-image:0.7 .

#lint-job:
#  stage: lint
#  script:
#    -
#
#format-job:
#  stage: format
#  script:
#    -
#
#typecheck-job:
#  stage: typecheck
#  script:
#    -
#
#migrate-job:
#  stage: migrate
#  image: docker exec -rm booking-app-image:0.7
#  script:
#    -

test-job:
  stage: test
  script:
    - docker run --rm -it booking-app-image:0.7 poetry run pytest


deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose --file docker-compose-ci.yml up -d
    - docker exec nginx-booking nginx -s reload
