services:
  backend-app:
    networks:
      - booking-network
    container_name: 'app-cont'
    image: booking-app-image:0.7
    volumes:
      - images_for_app:/app/src/static/images/
#    ports:
#      - "8888:8000"




  celery-worker:
    networks:
      - booking-network
    container_name: 'celery-worker-cont'
    image: booking-app-image:0.7
    volumes:
      - images_for_app:/app/src/static/images/
    command: [ "celery", "--app=src.celery_tasks.celery_app:celery_inst", "worker", "--loglevel", "INFO" ]



  celery-beat:
    networks:
      - booking-network
    container_name: 'celery-beat-cont'
    image: booking-app-image:0.7
    volumes:
      - images_for_app:/app/src/static/images/
    command: [ "celery", "--app=src.celery_tasks.celery_app:celery_inst", "beat", "--loglevel", "INFO" ]

volumes:
  images_for_app:


networks:
  booking-network:
    external: true # позволяет работать сети между стеками docker compose

name: "booking"